//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_AllDocumentsView_VAWG
    {
        public Nullable<int> ObjType { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<int> DocNum { get; set; }
        public int DocEntry { get; set; }
        public int UseEffDate { get; set; }
        public string isCrin { get; set; }
    }
}
