//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_ActivityWithServiceCallsView
    {
        public int ObjType { get; set; }
        public int ClgCode { get; set; }
        public Nullable<System.DateTime> Recontact { get; set; }
        public string Action { get; set; }
        public Nullable<short> CntctType { get; set; }
        public string CntctTypeName { get; set; }
        public string CardCode { get; set; }
        public string custmrName { get; set; }
        public Nullable<short> AttendUser { get; set; }
        public Nullable<int> AttendEmpl { get; set; }
        public string Details { get; set; }
        public string Closed { get; set; }
        public string personal { get; set; }
        public string Notes { get; set; }
        public Nullable<short> CntctSbjct { get; set; }
        public string CntctSbjctname { get; set; }
        public Nullable<int> AtcEntry { get; set; }
        public string DocType { get; set; }
        public string DocEntry { get; set; }
        public Nullable<System.DateTime> CntctDate { get; set; }
        public Nullable<short> Location { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> BeginTime { get; set; }
        public Nullable<int> ENDTime { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public string DurType { get; set; }
        public Nullable<int> CntctCode { get; set; }
        public Nullable<int> status { get; set; }
        public string StatusName { get; set; }
        public string tentative { get; set; }
        public string Priority { get; set; }
        public string Reminder { get; set; }
        public Nullable<System.DateTime> RemDate { get; set; }
        public Nullable<short> RemTime { get; set; }
        public Nullable<decimal> RemQty { get; set; }
        public string RemType { get; set; }
        public Nullable<int> SlpCode { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string room { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string parentType { get; set; }
        public Nullable<int> parentId { get; set; }
        public Nullable<int> prevActvty { get; set; }
        public Nullable<int> CntctTime { get; set; }
        public Nullable<int> OprId { get; set; }
        public Nullable<int> OprLine { get; set; }
        public string RecurPat { get; set; }
        public Nullable<int> SeriesNum { get; set; }
        public Nullable<int> AssignedBy { get; set; }
        public string inactive { get; set; }
        public string IsRemoved { get; set; }
        public Nullable<int> technician { get; set; }
        public string SchClosed { get; set; }
    }
}
