//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_BasedDocsVatView
    {
        public int AbsEntry { get; set; }
        public int LineSeq { get; set; }
        public string SrcObjType { get; set; }
        public int SrcObjAbs { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> SrcArrType { get; set; }
        public Nullable<int> SrcLineNum { get; set; }
        public Nullable<int> SrcGrpNum { get; set; }
        public Nullable<decimal> BaseSum { get; set; }
        public Nullable<decimal> VatSum { get; set; }
        public Nullable<decimal> DeductSum { get; set; }
        public Nullable<decimal> EqSum { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public Nullable<int> FolioNum { get; set; }
        public string FolioPref { get; set; }
        public string StaCode { get; set; }
        public Nullable<int> StaType { get; set; }
        public string DocType { get; set; }
        public Nullable<System.DateTime> VatDate { get; set; }
        public string LicTradNum { get; set; }
        public Nullable<short> Series { get; set; }
        public string CANCELED { get; set; }
    }
}
