//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_DocItemView
    {
        public int DocItemType { get; set; }
        public string DocItemCode { get; set; }
        public string DocItemName { get; set; }
        public string DocItemAsInventory { get; set; }
    }
}
