//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_DocLineView
    {
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public string ObjType { get; set; }
        public int ArrayType { get; set; }
        public string TaxOnly { get; set; }
        public string CEECFlag { get; set; }
        public Nullable<int> CiOppLineN { get; set; }
        public string AcctCode { get; set; }
        public string MYFtype { get; set; }
    }
}
