//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_DocInstallmentsView
    {
        public int DocEntry { get; set; }
        public short InstlmntID { get; set; }
        public string ObjType { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string NumAtCard { get; set; }
        public Nullable<int> SlpCode { get; set; }
        public Nullable<decimal> InsTotal { get; set; }
        public Nullable<decimal> InsTotalFC { get; set; }
        public Nullable<decimal> InsTotalSy { get; set; }
        public string BlockDunn { get; set; }
        public Nullable<int> DunnLevel { get; set; }
        public string IsSales { get; set; }
        public string IsDunnable { get; set; }
        public string PeyMethod { get; set; }
    }
}
