//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_DocLinkedDownpaymentsView
    {
        public string ObjType { get; set; }
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public int LineSeq { get; set; }
        public int ArrayType { get; set; }
        public Nullable<int> LinkedObjType { get; set; }
        public Nullable<int> LinkedDocEntry { get; set; }
        public string VatGroup { get; set; }
        public string TaxCode { get; set; }
        public string IsLinkedDPMPosted { get; set; }
    }
}
