//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_DeferredDocTotalsView
    {
        public string ObjType { get; set; }
        public int AbsEntry { get; set; }
        public Nullable<decimal> BaseSum { get; set; }
        public Nullable<decimal> VatSum { get; set; }
        public Nullable<decimal> EqSum { get; set; }
        public Nullable<decimal> DeductSum { get; set; }
        public Nullable<decimal> TotalSum { get; set; }
    }
}
