//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_EDFLatestLogsView
    {
        public int AbsEntry { get; set; }
        public int LogNum { get; set; }
        public string LogType { get; set; }
        public string LogMessage { get; set; }
        public string LogData { get; set; }
        public Nullable<System.DateTime> LogOpDate { get; set; }
        public Nullable<int> LogOpTS { get; set; }
        public Nullable<int> ExportFmt { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateTS { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateTS { get; set; }
        public Nullable<short> LogInstanc { get; set; }
        public Nullable<int> RankByDT { get; set; }
    }
}
