//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_ElectronicDocumentLogViewMX
    {
        public int AbsEntry { get; set; }
        public string Code { get; set; }
        public string ActType { get; set; }
        public string ActStatus { get; set; }
        public string ActDesc { get; set; }
        public string ActMessage { get; set; }
        public Nullable<int> ActEnv { get; set; }
        public string SrcObjType { get; set; }
        public Nullable<int> SrcObjAbs { get; set; }
        public Nullable<short> Submits { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<int> SendTime { get; set; }
        public Nullable<System.DateTime> LogOpDate { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string IsRemoved { get; set; }
        public string Cancelation { get; set; }
        public string SendData { get; set; }
        public string RecvData { get; set; }
        public string UUID { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> Series { get; set; }
        public string DocCanceled { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public Nullable<System.DateTime> DocCreateDate { get; set; }
        public Nullable<int> DocCreateTime { get; set; }
        public string ReceptorRFC { get; set; }
        public string EDocTest { get; set; }
        public string EmisorRFC { get; set; }
        public string PAC { get; set; }
        public string PACUsrName { get; set; }
        public string PACPasswrd { get; set; }
        public string CertID { get; set; }
        public string GenType { get; set; }
    }
}
