//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_ElectronicDocumentLogViewBR
    {
        public int AbsEntry { get; set; }
        public string ActType { get; set; }
        public string ActStatus { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<short> SeqCode { get; set; }
        public string NfeSeries { get; set; }
        public string NfeModel { get; set; }
        public string TaxId0 { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string CountryS { get; set; }
        public string CityS { get; set; }
        public string AssignedID { get; set; }
        public Nullable<short> Submits { get; set; }
        public Nullable<System.DateTime> MdCreateDate { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string ActMessage { get; set; }
        public Nullable<int> EnvType { get; set; }
        public string ObjType { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public string SrcObjType { get; set; }
        public Nullable<int> SrcObjAbs { get; set; }
        public Nullable<int> NFeNoFrom { get; set; }
        public Nullable<int> NFeNoTo { get; set; }
        public Nullable<short> Year { get; set; }
        public string Reason { get; set; }
        public Nullable<int> CreateTS { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateTime { get; set; }
        public string Code { get; set; }
        public string ObjectID { get; set; }
        public string ReportID { get; set; }
        public Nullable<int> BPLId { get; set; }
        public string DocBtch { get; set; }
        public Nullable<short> DocBtchLn { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.DateTime> RecvDate { get; set; }
        public string Carrier { get; set; }
        public string SendData { get; set; }
        public string RecvData { get; set; }
        public string IsRemoved { get; set; }
        public string CANCELED { get; set; }
        public string EDocGenTyp { get; set; }
        public string Cancel { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> SendTime { get; set; }
    }
}
