//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_FolioNumbersView
    {
        public Nullable<int> FolSeries { get; set; }
        public Nullable<int> FolNumFrom { get; set; }
        public Nullable<int> FolNumTo { get; set; }
        public string ObjType { get; set; }
        public int DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DocSubType { get; set; }
        public string PTICode { get; set; }
        public string Letter { get; set; }
        public string CANCELED { get; set; }
    }
}
