//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_JournalEntryFirstTaxIdOrBPView
    {
        public int TransID { get; set; }
        public int LineID { get; set; }
        public string TaxID { get; set; }
        public string BPCode { get; set; }
    }
}
