//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_MarketingDocumentsView_AR
    {
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public Nullable<System.DateTime> VatDate { get; set; }
        public Nullable<int> DocNum { get; set; }
        public string LicTradNum { get; set; }
        public Nullable<short> Series { get; set; }
        public string CANCELED { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateTS { get; set; }
        public string IsDraft { get; set; }
        public Nullable<int> BPLId { get; set; }
        public Nullable<int> FolNumFrom { get; set; }
        public Nullable<int> FolNumTo { get; set; }
        public string PTICode { get; set; }
        public string Letter { get; set; }
        public Nullable<int> EDocExpFrm { get; set; }
        public int DocEntry { get; set; }
        public string ObjType { get; set; }
        public Nullable<int> FolSeries { get; set; }
    }
}
