//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_MarketingDocumentsView
    {
        public string DocType { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public Nullable<System.DateTime> VatDate { get; set; }
        public Nullable<int> DocNum { get; set; }
        public string LicTradNum { get; set; }
        public string NumAtCard { get; set; }
        public Nullable<short> Series { get; set; }
        public string DocCur { get; set; }
        public Nullable<decimal> DocRate { get; set; }
        public Nullable<int> FinncPriod { get; set; }
        public string Address { get; set; }
        public string CANCELED { get; set; }
        public string JrnlMemo { get; set; }
        public int DocEntry { get; set; }
        public string ObjType { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string Indicator { get; set; }
        public string InsurOp347 { get; set; }
        public string ResidenNum { get; set; }
        public string PayToCode { get; set; }
        public string IsICT { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> CIG { get; set; }
        public Nullable<int> CUP { get; set; }
        public Nullable<short> SeqCode { get; set; }
        public Nullable<int> Serial { get; set; }
        public string SeriesStr { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateTS { get; set; }
        public string IsDraft { get; set; }
        public string EDocGenTyp { get; set; }
        public Nullable<int> BPLId { get; set; }
        public string EDocTest { get; set; }
        public Nullable<int> FolNumFrom { get; set; }
        public Nullable<int> FolNumTo { get; set; }
        public string DocStatus { get; set; }
        public string SplitPmnt { get; set; }
    }
}
