//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_OOCRView
    {
        public string OcrCode { get; set; }
        public string OcrName { get; set; }
        public Nullable<decimal> OcrTotal { get; set; }
        public string Direct { get; set; }
        public string Locked { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<short> DimCode { get; set; }
        public Nullable<int> AbsEntry { get; set; }
        public string Active { get; set; }
        public Nullable<int> logInstanc { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    }
}
