//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_PaymentLinesView
    {
        public string ObjType { get; set; }
        public int DocNum { get; set; }
        public int LineId { get; set; }
        public string InvType { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public string AcctCode { get; set; }
        public Nullable<int> BPLId { get; set; }
    }
}
