//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_PaymentsView
    {
        public string DocType { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public Nullable<System.DateTime> VatDate { get; set; }
        public int DocNum { get; set; }
        public Nullable<short> Series { get; set; }
        public string DocCurr { get; set; }
        public Nullable<decimal> DocRate { get; set; }
        public Nullable<int> FinncPriod { get; set; }
        public string Canceled { get; set; }
        public string JrnlMemo { get; set; }
        public string TransCode { get; set; }
        public int DocEntry { get; set; }
        public string ObjType { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string ResidenNum { get; set; }
        public string OperatCode { get; set; }
        public string PayToCode { get; set; }
        public string Address { get; set; }
        public Nullable<int> CIG { get; set; }
        public Nullable<int> CUP { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateTS { get; set; }
        public string Comments { get; set; }
    }
}
