//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_PaymentMeansPerDateView
    {
        public string PayObjType { get; set; }
        public int PayAbsEntry { get; set; }
        public int MeansType { get; set; }
        public int MeansLine { get; set; }
        public Nullable<int> MeansAbsEntry { get; set; }
        public Nullable<int> MeansID { get; set; }
        public string MeansStrID { get; set; }
        public Nullable<System.DateTime> MeansDate { get; set; }
        public Nullable<decimal> MeansDateTotal { get; set; }
        public Nullable<decimal> DocTotalSum { get; set; }
        public Nullable<decimal> MeansPart { get; set; }
    }
}
