//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_PaymentsByPayMeansView
    {
        public string ObjType { get; set; }
        public int AbsEntry { get; set; }
        public int Num { get; set; }
        public string Type { get; set; }
        public string Cancelled { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public Nullable<System.DateTime> VatDate { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Branch { get; set; }
        public string OperationCode { get; set; }
        public string CardCode { get; set; }
        public int DocPayMeansType { get; set; }
        public int DocPayMeansLineID { get; set; }
        public Nullable<int> DocPayMeansID { get; set; }
        public string DocObjType { get; set; }
        public Nullable<int> DocAbsEntry { get; set; }
        public int DocTransID { get; set; }
        public Nullable<int> DocPayMeansNum { get; set; }
        public string DocPayMeansNumStr { get; set; }
        public Nullable<decimal> DocPayMeansSum { get; set; }
        public int DocPayMeansVat { get; set; }
    }
}
