//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_SnBOITL1OnhCnlView
    {
        public int LogEntry { get; set; }
        public string ItemCode { get; set; }
        public int SysNumber { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> AllocQty { get; set; }
        public Nullable<int> MdAbsEntry { get; set; }
        public Nullable<decimal> ReleaseQty { get; set; }
        public Nullable<decimal> PickedQty { get; set; }
    }
}
