//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_SnBOpenQtyView
    {
        public Nullable<int> DocType { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public Nullable<int> DocLine { get; set; }
        public Nullable<int> DocSubLine { get; set; }
        public Nullable<int> ManagedBy { get; set; }
        public string ItemCode { get; set; }
        public int SysNumber { get; set; }
        public string LocCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    }
}
