//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_SnBOpenQtyInnerViewAlloc
    {
        public Nullable<int> AllocateTp { get; set; }
        public Nullable<int> AllocatEnt { get; set; }
        public Nullable<int> AllocateLn { get; set; }
        public Nullable<int> AppSubLine { get; set; }
        public Nullable<int> ManagedBy { get; set; }
        public int LogEntry { get; set; }
        public string ItemCode { get; set; }
        public int SysNumber { get; set; }
        public string LocCode { get; set; }
        public Nullable<int> TransId { get; set; }
        public Nullable<decimal> AllocQty { get; set; }
    }
}
