//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_SnBReallocDocPathsView
    {
        public Nullable<int> ApplyType { get; set; }
        public Nullable<int> ApplyEntry { get; set; }
        public Nullable<int> ApplyLine { get; set; }
        public int AppSubLine { get; set; }
        public int DocType { get; set; }
        public int DocEntry { get; set; }
        public int DocLine { get; set; }
        public int DocSubLine { get; set; }
    }
}
