//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_SnB1stAllocDocView
    {
        public Nullable<int> SnB1stAllocViewLogEntry { get; set; }
        public Nullable<int> SnB1stAllocViewDocType { get; set; }
        public Nullable<int> SnB1stAllocViewDocEntry { get; set; }
        public Nullable<int> SnB1stAllocViewDocNum { get; set; }
        public Nullable<int> SnB1stAllocViewMngBy { get; set; }
        public Nullable<int> SnB1stAllocViewSnbMdAbs { get; set; }
        public string SnB1stAllocViewItemCode { get; set; }
        public int SnB1stAllocViewSnbSysNum { get; set; }
        public string SnB1stAllocViewLocCode { get; set; }
        public Nullable<decimal> SnB1stAllocViewAllocQty { get; set; }
    }
}
