//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_SnBAllocateDocView
    {
        public Nullable<int> SnBAllocateViewLogEntry { get; set; }
        public Nullable<int> SnBAllocateViewDocType { get; set; }
        public Nullable<int> SnBAllocateViewDocEntry { get; set; }
        public Nullable<int> SnBAllocateViewDocLine { get; set; }
        public Nullable<int> SnBAllocateViewMngBy { get; set; }
        public Nullable<int> SnBAllocateViewSnbMdAbs { get; set; }
        public string SnBAllocateViewItemCode { get; set; }
        public int SnBAllocateViewSnbSysNum { get; set; }
        public string SnBAllocateViewLocCode { get; set; }
        public Nullable<decimal> SnBAllocateViewAllocQty { get; set; }
    }
}
