//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_VatAcctView
    {
        public string SrcObjType { get; set; }
        public int SrcObjAbs { get; set; }
        public Nullable<int> SrcArrType { get; set; }
        public Nullable<int> SrcLineNum { get; set; }
        public Nullable<int> SrcGrpNum { get; set; }
        public string IsDeferred { get; set; }
        public string AcctCode { get; set; }
        public Nullable<int> TAX1LinSeq { get; set; }
    }
}
