//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_VatView
    {
        public int AbsEntry { get; set; }
        public string SrcObjType { get; set; }
        public int SrcObjAbs { get; set; }
        public int OrdinLNum { get; set; }
        public int LineSeq { get; set; }
        public Nullable<int> SrcArrType { get; set; }
        public Nullable<int> SrcLineNum { get; set; }
        public Nullable<int> SrcGrpNum { get; set; }
        public string Code { get; set; }
        public string StaCode { get; set; }
        public Nullable<int> StaType { get; set; }
        public string IsLiable { get; set; }
        public string TaxType { get; set; }
        public string IsAcq { get; set; }
        public string Isdeferred { get; set; }
        public Nullable<decimal> VatPercent { get; set; }
        public Nullable<decimal> NdPercent { get; set; }
        public Nullable<decimal> EqPercent { get; set; }
        public string CrditDebit { get; set; }
        public string BaseObjTyp { get; set; }
        public Nullable<int> BaseAbs { get; set; }
        public Nullable<int> BaseArrTyp { get; set; }
        public Nullable<int> BaseLinNum { get; set; }
        public Nullable<int> BaseGrpNum { get; set; }
        public Nullable<decimal> BaseSum { get; set; }
        public Nullable<decimal> BaseSumSc { get; set; }
        public Nullable<decimal> BaseSumFc { get; set; }
        public Nullable<decimal> VatSum { get; set; }
        public Nullable<decimal> VatSumSc { get; set; }
        public Nullable<decimal> VatSumFc { get; set; }
        public Nullable<decimal> DeductSum { get; set; }
        public Nullable<decimal> DedctSumSC { get; set; }
        public Nullable<decimal> DedctSumFC { get; set; }
        public Nullable<decimal> EqSum { get; set; }
        public Nullable<decimal> EqSumSC { get; set; }
        public Nullable<decimal> EqSumFC { get; set; }
        public string Name { get; set; }
        public string IsEC { get; set; }
        public string TriangularDeal { get; set; }
        public string GoddsShip { get; set; }
        public string Category { get; set; }
        public string DocType { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public Nullable<System.DateTime> VatDate { get; set; }
        public Nullable<int> DocNum { get; set; }
        public string LicTradNum { get; set; }
        public string NumAtCard { get; set; }
        public Nullable<int> Series { get; set; }
        public string DocCur { get; set; }
        public Nullable<decimal> DocRate { get; set; }
        public Nullable<int> FinncPriod { get; set; }
        public string Address { get; set; }
        public string CANCELED { get; set; }
        public string JrnlMemo { get; set; }
        public string WTCode { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string CardType { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string BPLicTradNum { get; set; }
        public string VatIdUnCmp { get; set; }
        public string AddID { get; set; }
        public string Indicator { get; set; }
        public string InsurOp347 { get; set; }
        public string ResidenNum { get; set; }
        public string OperatCode { get; set; }
        public string PayToCode { get; set; }
        public string IsICT { get; set; }
        public string ServSupply { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> CIG { get; set; }
        public Nullable<int> CUP { get; set; }
        public string ActType { get; set; }
        public string IsSplitPay { get; set; }
        public Nullable<int> BPLId { get; set; }
    }
}
