//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_WTaxBaseDocView
    {
        public string ObjType { get; set; }
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public int Factor { get; set; }
        public string CardCode { get; set; }
        public int ArrayOffset { get; set; }
        public int LineNum { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> Freight { get; set; }
        public Nullable<decimal> NetSumLC { get; set; }
        public Nullable<decimal> NetSumSC { get; set; }
        public Nullable<decimal> NetSumFC { get; set; }
        public Nullable<decimal> VatSumLC { get; set; }
        public Nullable<decimal> VatSumSC { get; set; }
        public Nullable<decimal> VatSumFC { get; set; }
        public Nullable<decimal> WTaxSumLC { get; set; }
        public Nullable<decimal> WTaxSumSC { get; set; }
        public Nullable<decimal> WTaxSumFC { get; set; }
        public Nullable<decimal> WTaxNoVATWLC { get; set; }
        public Nullable<decimal> WTaxNoVATWSC { get; set; }
        public Nullable<decimal> WTaxNoVATWFC { get; set; }
    }
}
