//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_WTaxSumsPerWhtTypeView
    {
        public string SrcObjType { get; set; }
        public int SrcObjAbs { get; set; }
        public Nullable<int> SrcArrType { get; set; }
        public Nullable<int> SrcLineNum { get; set; }
        public Nullable<int> SrcGrpNum { get; set; }
        public string BaseObjTyp { get; set; }
        public Nullable<int> BaseAbs { get; set; }
        public Nullable<int> BaseArrTyp { get; set; }
        public Nullable<int> BaseLinNum { get; set; }
        public Nullable<int> BaseGrpNum { get; set; }
        public string WhtType { get; set; }
        public Nullable<decimal> WTaxSum { get; set; }
        public Nullable<decimal> WTaxSumSc { get; set; }
        public Nullable<decimal> WTaxSumFc { get; set; }
    }
}
