//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_WTaxView
    {
        public string WTaxAbsId { get; set; }
        public string ObjType { get; set; }
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public int Factor { get; set; }
        public string CardCode { get; set; }
        public string FullCopied { get; set; }
        public string BaseObjTyp { get; set; }
        public string BaseType { get; set; }
        public Nullable<decimal> BaseNetSum { get; set; }
        public Nullable<decimal> BaseNetSC { get; set; }
        public Nullable<decimal> BaseNetFC { get; set; }
        public Nullable<decimal> BaseVatSum { get; set; }
        public Nullable<decimal> BaseVatSC { get; set; }
        public Nullable<decimal> BaseVatFC { get; set; }
        public Nullable<decimal> BaseGrossSumLC { get; set; }
        public Nullable<decimal> BaseGrossSumSC { get; set; }
        public Nullable<decimal> BaseGrossSumFC { get; set; }
        public Nullable<decimal> BaseGrossVATSumLC { get; set; }
        public Nullable<decimal> BaseGrossVATSumSC { get; set; }
        public Nullable<decimal> BaseGrossVATSumFC { get; set; }
        public Nullable<decimal> TxblSum { get; set; }
        public Nullable<decimal> TxblSumSc { get; set; }
        public Nullable<decimal> TxblSumFc { get; set; }
        public Nullable<decimal> WTaxSum { get; set; }
        public Nullable<decimal> WTaxSumSc { get; set; }
        public Nullable<decimal> WTaxSumFc { get; set; }
        public int AbsEntry { get; set; }
        public int LineSeq { get; set; }
        public Nullable<decimal> DocRate { get; set; }
        public Nullable<decimal> SysRate { get; set; }
    }
}
