//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1_WAVGListOfTransactionsView
    {
        public int MessageID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> TransType { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public Nullable<int> DocLineNum { get; set; }
        public Nullable<int> BaseType { get; set; }
        public Nullable<int> BaseAbsEnt { get; set; }
        public Nullable<int> BaseLine { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> DocPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string PriceCurr { get; set; }
        public Nullable<decimal> TotalLC { get; set; }
        public Nullable<decimal> TotalFC { get; set; }
        public Nullable<decimal> TotalSC { get; set; }
        public Nullable<decimal> DocTotal { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> DocRate { get; set; }
        public string LocCode { get; set; }
        public string BPCardCode { get; set; }
        public string PrjCode { get; set; }
        public Nullable<int> AccumType { get; set; }
        public Nullable<int> ActionType { get; set; }
        public Nullable<System.DateTime> System_Date { get; set; }
        public Nullable<System.DateTime> Effective_Posting_Date { get; set; }
        public Nullable<System.DateTime> Posting_Date { get; set; }
        public Nullable<int> DocNum { get; set; }
        public string isCrin { get; set; }
    }
}
