//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO
    {
        public int DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public string DocType { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string NumAtCard { get; set; }
        public Nullable<decimal> DocTotal { get; set; }
        public string Ref1 { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> DocTotalSy { get; set; }
        public Nullable<decimal> PaidSys { get; set; }
        public string U_FacNum { get; set; }
        public string U_FacNom { get; set; }
        public Nullable<int> slpcode { get; set; }
        public Nullable<short> series { get; set; }
        public string u_cod_factura { get; set; }
    }
}
