//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class facnc1
    {
        public string ItemCode { get; set; }
        public string Dscription { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public string bodega { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public Nullable<int> SlpCode { get; set; }
        public string WhsCode { get; set; }
        public string WhsName { get; set; }
        public Nullable<decimal> GrossBuyPr { get; set; }
        public Nullable<decimal> PriceBefDi { get; set; }
        public string U_transporte { get; set; }
        public string U_facnum { get; set; }
        public Nullable<short> Series { get; set; }
        public Nullable<decimal> StockPrice { get; set; }
        public Nullable<decimal> PriceAfVAT { get; set; }
        public Nullable<decimal> INMPrice { get; set; }
        public Nullable<decimal> StockValue { get; set; }
        public Nullable<short> groupnum { get; set; }
        public string U_Cod_Sucursal { get; set; }
    }
}
