//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturacion_diaria
    {
        public Nullable<System.DateTime> Fecha_Contabilizacion { get; set; }
        public Nullable<int> NOImpresos { get; set; }
        public Nullable<int> CorrelativoCorte { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public string Codigo_SN { get; set; }
        public string Nombre_SN { get; set; }
        public string Fact_a_Nombre_de { get; set; }
        public string Numero_Documento { get; set; }
        public string Tipo_fact { get; set; }
        public Nullable<int> Numero_SAP { get; set; }
        public int Interno_SAP { get; set; }
        public Nullable<decimal> Desc_Antici { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<decimal> Percepcion { get; set; }
        public Nullable<decimal> C__Anticipo { get; set; }
        public Nullable<decimal> Valor_Anticipo { get; set; }
        public Nullable<decimal> Total_Documento { get; set; }
        public Nullable<decimal> Pagado_Abono { get; set; }
        public Nullable<decimal> Neto { get; set; }
        public Nullable<int> Cod__Vendedor { get; set; }
        public Nullable<System.DateTime> Fecha_Libros { get; set; }
        public string Nit { get; set; }
        public string Registro { get; set; }
        public Nullable<short> GroupNum { get; set; }
        public string U_Tipo_venta { get; set; }
        public string U_Tiponc { get; set; }
    }
}
