//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class IBT1_LINK
    {
        public Nullable<int> LogEntry { get; set; }
        public string ItemCode { get; set; }
        public string BatchNum { get; set; }
        public string WhsCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> BaseType { get; set; }
        public Nullable<int> BaseEntry { get; set; }
        public Nullable<int> BaseNum { get; set; }
        public Nullable<int> BaseLinNum { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public int Direction { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> BsDocType { get; set; }
        public Nullable<int> BsDocEntry { get; set; }
        public Nullable<int> BsDocLine { get; set; }
        public string DataSource { get; set; }
        public Nullable<int> UserSign { get; set; }
    }
}
