//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class OINM
    {
        public Nullable<int> TransNum { get; set; }
        public Nullable<int> TransType { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string BASE_REF { get; set; }
        public Nullable<int> DocLineNum { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string Comments { get; set; }
        public string JrnlMemo { get; set; }
        public Nullable<short> DocTime { get; set; }
        public string ItemCode { get; set; }
        public string Dscription { get; set; }
        public Nullable<decimal> InQty { get; set; }
        public Nullable<decimal> OutQty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string VendorNum { get; set; }
        public string SerialNum { get; set; }
        public string Warehouse { get; set; }
        public string TreeType { get; set; }
        public Nullable<int> SlpCode { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public string DataSource { get; set; }
        public string PrjCode { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string BlockNum { get; set; }
        public string ImportLog { get; set; }
        public string UseDocPric { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<decimal> CalcPrice { get; set; }
        public Nullable<decimal> OpenQty { get; set; }
        public Nullable<int> Instance { get; set; }
        public int LastInst { get; set; }
        public Nullable<decimal> RevalTotal { get; set; }
        public string BaseCurr { get; set; }
        public Nullable<int> ApplObj { get; set; }
        public Nullable<int> AppObjAbs { get; set; }
        public string AppObjType { get; set; }
        public string StockAct { get; set; }
        public string TrnsfrAct { get; set; }
        public string PriceDifAc { get; set; }
        public string VarianceAc { get; set; }
        public string ReturnAct { get; set; }
        public string ExcRateAct { get; set; }
        public string ClearAct { get; set; }
        public string CostAct { get; set; }
        public string WipAct { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> BaseLine { get; set; }
        public Nullable<decimal> TransValue { get; set; }
        public Nullable<decimal> PriceDiff { get; set; }
        public int TransSeq { get; set; }
        public string InvntAct { get; set; }
        public string RemMethod { get; set; }
        public Nullable<decimal> OpenValue { get; set; }
        public Nullable<int> SubLineNum { get; set; }
        public Nullable<int> AppObjLine { get; set; }
        public Nullable<decimal> Expenses { get; set; }
        public Nullable<decimal> OpenExp { get; set; }
        public Nullable<decimal> Allocation { get; set; }
        public Nullable<decimal> OpenAlloc { get; set; }
        public Nullable<decimal> ExpAlloc { get; set; }
        public Nullable<decimal> OExpAlloc { get; set; }
        public Nullable<decimal> OpenPDiff { get; set; }
        public Nullable<decimal> ExchDiff { get; set; }
        public Nullable<decimal> OpenEDiff { get; set; }
        public Nullable<decimal> NegInvAdjs { get; set; }
        public Nullable<decimal> OpenNegInv { get; set; }
        public string NegStckAct { get; set; }
        public int BTransVal { get; set; }
        public Nullable<decimal> VarVal { get; set; }
        public Nullable<decimal> BExpVal { get; set; }
        public Nullable<decimal> CogsVal { get; set; }
        public Nullable<decimal> BNegAVal { get; set; }
        public string IOffIncAcc { get; set; }
        public Nullable<decimal> IOffIncVal { get; set; }
        public string DOffDecAcc { get; set; }
        public Nullable<decimal> DOffDecVal { get; set; }
        public string DecAcc { get; set; }
        public Nullable<decimal> DecVal { get; set; }
        public Nullable<decimal> WipVal { get; set; }
        public string WipVarAcc { get; set; }
        public Nullable<decimal> WipVarVal { get; set; }
        public string IncAct { get; set; }
        public Nullable<decimal> IncVal { get; set; }
        public string ExpCAcc { get; set; }
        public string CostMethod { get; set; }
        public string OcrCode { get; set; }
        public int BaseQty { get; set; }
        public int PrevTrans { get; set; }
        public int HTransSeq { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string OcrCode4 { get; set; }
        public string OcrCode5 { get; set; }
    }
}
