//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSRD
    {
        public string ItemCode { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> DocLineNum { get; set; }
        public Nullable<decimal> DocQuty { get; set; }
        public Nullable<decimal> DocOpenQty { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string Status { get; set; }
        public int SrdType { get; set; }
        public string ItemName { get; set; }
        public string WhsCode { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string ManOutOnly { get; set; }
        public string Direction { get; set; }
        public Nullable<int> CreateNew { get; set; }
        public string DataSource { get; set; }
        public Nullable<int> UserSign { get; set; }
    }
}
