//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSRI
    {
        public string ItemCode { get; set; }
        public int SysSerial { get; set; }
        public string SuppSerial { get; set; }
        public string IntrSerial { get; set; }
        public string BatchId { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<System.DateTime> PrdDate { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<System.DateTime> GrntStart { get; set; }
        public Nullable<System.DateTime> GrntExp { get; set; }
        public string WhsCode { get; set; }
        public string Located { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> BaseType { get; set; }
        public Nullable<int> BaseEntry { get; set; }
        public Nullable<int> BaseNum { get; set; }
        public Nullable<int> BaseLinNum { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string ItemName { get; set; }
        public int Status { get; set; }
        public int Direction { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string Transfered { get; set; }
        public Nullable<short> Instance { get; set; }
    }
}
