//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagos_Clientes
    {
        public int DocNum { get; set; }
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string JrnlMemo { get; set; }
        public Nullable<decimal> CashSum { get; set; }
        public Nullable<decimal> CheckSum { get; set; }
        public Nullable<int> CheckNum { get; set; }
        public string BankCode { get; set; }
        public Nullable<decimal> TrsfrSum { get; set; }
        public Nullable<decimal> CreditSum { get; set; }
        public string CrCardNum { get; set; }
        public Nullable<decimal> DocTotal { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string DocNumber { get; set; }
    }
}
