//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagos_recibidos
    {
        public int DocNum { get; set; }
        public int DocEntry { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string u_tipo_pago { get; set; }
        public string u_tipo_venta { get; set; }
        public string U_TipoNC { get; set; }
        public string JrnlMemo { get; set; }
        public Nullable<decimal> CashSum { get; set; }
        public Nullable<decimal> TrsfrSum { get; set; }
        public Nullable<decimal> checksum { get; set; }
        public Nullable<decimal> CreditSum { get; set; }
        public Nullable<decimal> VatSum { get; set; }
        public Nullable<decimal> Neto { get; set; }
        public Nullable<decimal> Total_Fact { get; set; }
        public Nullable<decimal> DocTotal { get; set; }
        public Nullable<decimal> SumApplied { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> baseAbs { get; set; }
        public Nullable<System.DateTime> FECHA_FAC { get; set; }
        public Nullable<int> SlpCode { get; set; }
        public string U_FacNum { get; set; }
        public Nullable<short> uSERSIGN { get; set; }
        public Nullable<short> series { get; set; }
    }
}
