//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBO_FI_GL_01
    {
        public string GL_ACCOUNT { get; set; }
        public string SBO_ALTACT { get; set; }
        public Nullable<decimal> DEBIT { get; set; }
        public Nullable<decimal> CREDIT { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public string FISCPER { get; set; }
        public string CURRENCY { get; set; }
        public string CURTYPE { get; set; }
    }
}
