//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBO_FI_PC_01
    {
        public string PROFIT_CTR { get; set; }
        public string SBOPFT_COD { get; set; }
        public string CRM_DIRECT { get; set; }
        public int AC_DOC_NO { get; set; }
        public string GL_ACCOUNT { get; set; }
        public string CALDAY { get; set; }
        public string ACCT_TYPE { get; set; }
        public Nullable<decimal> DEBIT { get; set; }
        public Nullable<decimal> CREDIT { get; set; }
        public string CURRENCY { get; set; }
    }
}
