//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBO_SALES_SO
    {
        public int DOCNUM { get; set; }
        public int LINENUM { get; set; }
        public string CANCELLED { get; set; }
        public string ITEMCODE { get; set; }
        public string CARDCODE { get; set; }
        public Nullable<int> SALESPERSON { get; set; }
        public string DOCDATE { get; set; }
        public string UPDATEDATE { get; set; }
        public Nullable<decimal> ORDERVALUE { get; set; }
        public Nullable<decimal> ORDERQUANTITY { get; set; }
        public Nullable<decimal> OPENORDQUANT { get; set; }
        public Nullable<decimal> GROSSBYEPR { get; set; }
        public string CURRENCY { get; set; }
        public string BASEUNIT { get; set; }
    }
}
