//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBO_PUR_GR_GRET
    {
        public string DOCENTRY { get; set; }
        public int LINENUM { get; set; }
        public string RETURNID { get; set; }
        public string ITEMCODE { get; set; }
        public string CARDCODE { get; set; }
        public string PODOCDATE { get; set; }
        public string DOCDATE { get; set; }
        public string CREATEDATE { get; set; }
        public string UPDATEDATE { get; set; }
        public Nullable<decimal> GRVALUE { get; set; }
        public Nullable<decimal> GRQUANTITY { get; set; }
        public string CURRENCY { get; set; }
        public string BASEUNIT { get; set; }
    }
}
