//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBO_FI_GL_02
    {
        public int AC_DOC_NO { get; set; }
        public int ITEM_NUM { get; set; }
        public string GL_ACCOUNT { get; set; }
        public string SBO_ALTACT { get; set; }
        public Nullable<decimal> DEBIT_LC { get; set; }
        public Nullable<decimal> CREDIT_LC { get; set; }
        public string LOC_CURRCY { get; set; }
        public Nullable<decimal> SBOCRD_SC { get; set; }
        public Nullable<decimal> SBODBT_SC { get; set; }
        public string SBOSYS_CUR { get; set; }
        public Nullable<decimal> DEBIT_DC { get; set; }
        public Nullable<decimal> CREDIT_DC { get; set; }
        public string DOC_CURRCY { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public string NETDUEDATE { get; set; }
        public string REF_DOC_AA { get; set; }
        public Nullable<int> SBOTRN_TYP { get; set; }
        public string PSTNG_DATE { get; set; }
        public string REF_KEY1 { get; set; }
        public string REF_KEY2 { get; set; }
        public Nullable<int> REF_KEY3 { get; set; }
        public string REF_DOC_NO { get; set; }
        public string OPP_REF { get; set; }
        public string SBOTRN_COD { get; set; }
        public string SBOPFT_COD { get; set; }
        public string SBOTX_DATE { get; set; }
        public Nullable<int> BATCH { get; set; }
        public string SBOVAT_GRP { get; set; }
        public Nullable<decimal> ID_BASE { get; set; }
        public Nullable<decimal> ID_TXRATE { get; set; }
        public string BBP_FLAG { get; set; }
        public string SBOADJ_IND { get; set; }
        public string SBOREV_IND { get; set; }
        public string CURRENCY { get; set; }
    }
}
