//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class VBIN
    {
        public int AbsEntry { get; set; }
        public string BinCode { get; set; }
        public string WhsCode { get; set; }
        public string SysBin { get; set; }
        public Nullable<int> SL1Abs { get; set; }
        public string SL1Code { get; set; }
        public Nullable<int> SL2Abs { get; set; }
        public string SL2Code { get; set; }
        public Nullable<int> SL3Abs { get; set; }
        public string SL3Code { get; set; }
        public Nullable<int> SL4Abs { get; set; }
        public string SL4Code { get; set; }
        public Nullable<int> Attr1Abs { get; set; }
        public string Attr1Val { get; set; }
        public Nullable<int> Attr2Abs { get; set; }
        public string Attr2Val { get; set; }
        public Nullable<int> Attr3Abs { get; set; }
        public string Attr3Val { get; set; }
        public Nullable<int> Attr4Abs { get; set; }
        public string Attr4Val { get; set; }
        public Nullable<int> Attr5Abs { get; set; }
        public string Attr5Val { get; set; }
        public Nullable<int> Attr6Abs { get; set; }
        public string Attr6Val { get; set; }
        public Nullable<int> Attr7Abs { get; set; }
        public string Attr7Val { get; set; }
        public Nullable<int> Attr8Abs { get; set; }
        public string Attr8Val { get; set; }
        public Nullable<int> Attr9Abs { get; set; }
        public string Attr9Val { get; set; }
        public Nullable<int> Attr10Abs { get; set; }
        public string Attr10Val { get; set; }
        public string Disabled { get; set; }
        public string Descr { get; set; }
        public string BarCode { get; set; }
        public string AltSortCod { get; set; }
        public Nullable<short> ItmRtrictT { get; set; }
        public string SpcItmCode { get; set; }
        public Nullable<short> SpcItmGrpC { get; set; }
        public string SngBatch { get; set; }
        public Nullable<short> RtrictType { get; set; }
        public string RtrictResn { get; set; }
        public Nullable<System.DateTime> RtrictDate { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string Transfered { get; set; }
        public Nullable<short> Instance { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Deleted { get; set; }
        public Nullable<decimal> MinLevel { get; set; }
        public Nullable<decimal> MaxLevel { get; set; }
        public string ReceiveBin { get; set; }
        public string NoAutoAllc { get; set; }
        public Nullable<decimal> MaxWeight1 { get; set; }
        public Nullable<short> Wght1Unit { get; set; }
        public Nullable<decimal> MaxWeight2 { get; set; }
        public Nullable<short> Wght2Unit { get; set; }
        public Nullable<short> UoMRtrict { get; set; }
        public Nullable<int> SpcUoMCode { get; set; }
        public Nullable<int> SpcUGPCode { get; set; }
        public Nullable<int> SngUoMCode { get; set; }
        public Nullable<int> BinAbs { get; set; }
        public Nullable<decimal> ItemQty { get; set; }
        public Nullable<int> ItemsNum { get; set; }
        public Nullable<int> SnBNum { get; set; }
        public Nullable<int> ItemWeight { get; set; }
    }
}
