//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class VBIN_Qty
    {
        public int BinAbs { get; set; }
        public Nullable<decimal> ItemQty { get; set; }
        public Nullable<int> ItemsNum { get; set; }
        public Nullable<int> SnBNum { get; set; }
        public Nullable<int> ItemWeight { get; set; }
    }
}
