//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DocEnvios
    {
        public Nullable<int> NumDoc { get; set; }
        public string U_FacNum { get; set; }
        public Nullable<System.DateTime> FechaDoc { get; set; }
        public Nullable<System.DateTime> FechaVenci { get; set; }
        public string CodCliente { get; set; }
        public string NomCliente { get; set; }
        public string DirCliente { get; set; }
        public Nullable<decimal> TotalDoc { get; set; }
        public string Ref1 { get; set; }
        public Nullable<short> ExtraMonth { get; set; }
        public Nullable<short> ExtraDays { get; set; }
        public string U_Tipo_Venta { get; set; }
        public string U_TipoNC { get; set; }
        public string U_Cod_Sucursal { get; set; }
        public int LineNum { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string ItemCode { get; set; }
        public string Dscription { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> TotalSumSy { get; set; }
        public string DiasCredito { get; set; }
    }
}
