//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDocs.Dao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Viktor2Entities : DbContext
    {
        public Viktor2Entities()
            : base("name=Viktor2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SBO_ACCOUNT_TEXT> SBO_ACCOUNT_TEXT { get; set; }
        public virtual DbSet<SBO_CUSTOMER_TEXT> SBO_CUSTOMER_TEXT { get; set; }
        public virtual DbSet<SBO_FI_GL_01> SBO_FI_GL_01 { get; set; }
        public virtual DbSet<SBO_FI_GL_02> SBO_FI_GL_02 { get; set; }
        public virtual DbSet<SBO_FI_PC_01> SBO_FI_PC_01 { get; set; }
        public virtual DbSet<SBO_MATERIAL_ATTR> SBO_MATERIAL_ATTR { get; set; }
        public virtual DbSet<SBO_MATERIAL_TEXT> SBO_MATERIAL_TEXT { get; set; }
        public virtual DbSet<SBO_PUR_GR_GRET> SBO_PUR_GR_GRET { get; set; }
        public virtual DbSet<SBO_PUR_IV_CM> SBO_PUR_IV_CM { get; set; }
        public virtual DbSet<SBO_PUR_PO> SBO_PUR_PO { get; set; }
        public virtual DbSet<SBO_SALES_DE> SBO_SALES_DE { get; set; }
        public virtual DbSet<SBO_SALES_IN> SBO_SALES_IN { get; set; }
        public virtual DbSet<SBO_SALES_SO> SBO_SALES_SO { get; set; }
        public virtual DbSet<B1_ActivityView> B1_ActivityView { get; set; }
        public virtual DbSet<B1_ActivityWithServiceCallsView> B1_ActivityWithServiceCallsView { get; set; }
        public virtual DbSet<B1_AllDocumentsView> B1_AllDocumentsView { get; set; }
        public virtual DbSet<B1_AllDocumentsView_VAWG> B1_AllDocumentsView_VAWG { get; set; }
        public virtual DbSet<B1_BasedDocsVatView> B1_BasedDocsVatView { get; set; }
        public virtual DbSet<B1_DeferredDocTotalsView> B1_DeferredDocTotalsView { get; set; }
        public virtual DbSet<B1_Doc12AddressView> B1_Doc12AddressView { get; set; }
        public virtual DbSet<B1_DocInstallmentsView> B1_DocInstallmentsView { get; set; }
        public virtual DbSet<B1_DocItemView> B1_DocItemView { get; set; }
        public virtual DbSet<B1_DocLineView> B1_DocLineView { get; set; }
        public virtual DbSet<B1_DocLinkedDownpaymentsView> B1_DocLinkedDownpaymentsView { get; set; }
        public virtual DbSet<B1_DocumentDataView> B1_DocumentDataView { get; set; }
        public virtual DbSet<B1_EDFLatestLogsView> B1_EDFLatestLogsView { get; set; }
        public virtual DbSet<B1_ElectronicDocumentLogViewBR> B1_ElectronicDocumentLogViewBR { get; set; }
        public virtual DbSet<B1_ElectronicDocumentLogViewMX> B1_ElectronicDocumentLogViewMX { get; set; }
        public virtual DbSet<B1_ElectronicDocumentView> B1_ElectronicDocumentView { get; set; }
        public virtual DbSet<B1_FolioNumbersView> B1_FolioNumbersView { get; set; }
        public virtual DbSet<B1_JournalEntryCustomerView> B1_JournalEntryCustomerView { get; set; }
        public virtual DbSet<B1_JournalEntryFirstTaxIdOrBPView> B1_JournalEntryFirstTaxIdOrBPView { get; set; }
        public virtual DbSet<B1_JournalEntryVendorView> B1_JournalEntryVendorView { get; set; }
        public virtual DbSet<B1_JournalTransSourceView> B1_JournalTransSourceView { get; set; }
        public virtual DbSet<B1_MarketingDocumentLinesView> B1_MarketingDocumentLinesView { get; set; }
        public virtual DbSet<B1_MarketingDocumentsView> B1_MarketingDocumentsView { get; set; }
        public virtual DbSet<B1_MarketingDocumentsView_AR> B1_MarketingDocumentsView_AR { get; set; }
        public virtual DbSet<B1_NLAuditFileOpeningDocView> B1_NLAuditFileOpeningDocView { get; set; }
        public virtual DbSet<B1_NotFullyCreditedDocView> B1_NotFullyCreditedDocView { get; set; }
        public virtual DbSet<B1_OinmWithBinTransfer> B1_OinmWithBinTransfer { get; set; }
        public virtual DbSet<B1_OinmWithoutBinTransfer> B1_OinmWithoutBinTransfer { get; set; }
        public virtual DbSet<B1_OOCRView> B1_OOCRView { get; set; }
        public virtual DbSet<B1_PaymentLinesView> B1_PaymentLinesView { get; set; }
        public virtual DbSet<B1_PaymentMeansDateTotalsView> B1_PaymentMeansDateTotalsView { get; set; }
        public virtual DbSet<B1_PaymentMeansPerDateView> B1_PaymentMeansPerDateView { get; set; }
        public virtual DbSet<B1_PaymentMeansView> B1_PaymentMeansView { get; set; }
        public virtual DbSet<B1_PaymentsByPayMeansView> B1_PaymentsByPayMeansView { get; set; }
        public virtual DbSet<B1_PaymentsView> B1_PaymentsView { get; set; }
        public virtual DbSet<B1_SnB1stAllocDocView> B1_SnB1stAllocDocView { get; set; }
        public virtual DbSet<B1_SnBAllocateDocView> B1_SnBAllocateDocView { get; set; }
        public virtual DbSet<B1_SnBOITL1OnhCnlView> B1_SnBOITL1OnhCnlView { get; set; }
        public virtual DbSet<B1_SnBOpenQtyInnerView> B1_SnBOpenQtyInnerView { get; set; }
        public virtual DbSet<B1_SnBOpenQtyInnerViewAlloc> B1_SnBOpenQtyInnerViewAlloc { get; set; }
        public virtual DbSet<B1_SnBOpenQtyView> B1_SnBOpenQtyView { get; set; }
        public virtual DbSet<B1_SnBOpenQtyViewAlloc> B1_SnBOpenQtyViewAlloc { get; set; }
        public virtual DbSet<B1_SnBOpenQtyViewForWTR> B1_SnBOpenQtyViewForWTR { get; set; }
        public virtual DbSet<B1_SnBReallocDocPathsView> B1_SnBReallocDocPathsView { get; set; }
        public virtual DbSet<B1_VatAcctView> B1_VatAcctView { get; set; }
        public virtual DbSet<B1_VatPerPaymentMeansView> B1_VatPerPaymentMeansView { get; set; }
        public virtual DbSet<B1_VatView> B1_VatView { get; set; }
        public virtual DbSet<B1_WAVGListOfTransactionsView> B1_WAVGListOfTransactionsView { get; set; }
        public virtual DbSet<B1_WTaxBaseDocView> B1_WTaxBaseDocView { get; set; }
        public virtual DbSet<B1_WTaxSumsPerWhtTypeView> B1_WTaxSumsPerWhtTypeView { get; set; }
        public virtual DbSet<B1_WTaxSumsView> B1_WTaxSumsView { get; set; }
        public virtual DbSet<B1_WTaxSumsWithoutVATWView> B1_WTaxSumsWithoutVATWView { get; set; }
        public virtual DbSet<B1_WTaxView> B1_WTaxView { get; set; }
        public virtual DbSet<DOC1_View> DOC1_View { get; set; }
        public virtual DbSet<ESTADO> ESTADO { get; set; }
        public virtual DbSet<facnc1> facnc1 { get; set; }
        public virtual DbSet<facturacion_diaria> facturacion_diaria { get; set; }
        public virtual DbSet<IBT1> IBT1 { get; set; }
        public virtual DbSet<IBT1_LINK> IBT1_LINK { get; set; }
        public virtual DbSet<ixvITL_LastWhs> ixvITL_LastWhs { get; set; }
        public virtual DbSet<ixvITL_Min> ixvITL_Min { get; set; }
        public virtual DbSet<OIBT> OIBT { get; set; }
        public virtual DbSet<OINM> OINM { get; set; }
        public virtual DbSet<OSRD> OSRD { get; set; }
        public virtual DbSet<OSRI> OSRI { get; set; }
        public virtual DbSet<pagos_Clientes> pagos_Clientes { get; set; }
        public virtual DbSet<pagos_recibidos> pagos_recibidos { get; set; }
        public virtual DbSet<SINM> SINM { get; set; }
        public virtual DbSet<SRI1> SRI1 { get; set; }
        public virtual DbSet<SRI1_LINK> SRI1_LINK { get; set; }
        public virtual DbSet<VBIN> VBIN { get; set; }
        public virtual DbSet<VBIN_Qty> VBIN_Qty { get; set; }
        public virtual DbSet<VentasporItem> VentasporItem { get; set; }
        public virtual DbSet<VentasporItemconsolidado> VentasporItemconsolidado { get; set; }
        public virtual DbSet<OINV> OINV { get; set; }
        public virtual DbSet<View_DocEnvios> View_DocEnvios { get; set; }
    }
}
